version: '3.1'

services:
  app:
    build: .
    container_name: divulgador_eventos_backend
    ports:
      - ${PORT}:${PORT}
    command: npm run start:prod
    environment:
      DATABASE_HOST: db
      REDIS_HOST: redis
    depends_on:
      - db
      - redis

  db:
    image: postgres
    restart: always
    container_name: divulgador_eventos_db
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - divulgador_eventos_data:/var/lib/postgresql/data

  redis:
    image: redis
    restart: always
    container_name: divulgador_eventos_redis
    command: redis-server --save 1 1 --appendonly yes --appendfsync always --port ${REDIS_PORT} --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - divulgador_eventos_redis_data:/data

volumes:
  divulgador_eventos_data:
  divulgador_eventos_redis_data:
